version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nscode-server
    ports:
      - 3000:8080
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    volumes:
      - './.docker/:/docker-entrypoint-initdb.d/'
